Try building Flet Studio iOS on CI

diff --git a/.appveyor.yml b/.appveyor.yml
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -23,75 +23,81 @@ environment:
     secure: V9nRzVDlIGS0a+dhkC2/vw==
 
   matrix:
-    - job_name: Build Flet package for Flutter
-      job_group: build_flet_package
-      APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004
 
-    - job_name: Build Flet for Windows
-      job_group: build_flet
-      job_depends_on: build_flet_package
-      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-
-    - job_name: Build Flet for macOS
+    - job_name: Build Flet Studio for iOS
       job_group: build_flet
       job_depends_on: build_flet_package
       APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
 
-    - job_name: Build Flet for Linux
-      job_group: build_flet
-      job_depends_on: build_flet_package
-      APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004
+    # - job_name: Build Flet package for Flutter
+    #   job_group: build_flet_package
+    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004
 
-    - job_name: Build Flet for Linux ARM64
-      job_group: build_flet
-      job_depends_on: build_flet_package
-      APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004-arm
-      python_stack: ""
+    # - job_name: Build Flet for Windows
+    #   job_group: build_flet
+    #   job_depends_on: build_flet_package
+    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
 
-    - job_name: Build Flet for iOS
-      job_group: build_flet
-      job_depends_on: build_flet_package
-      APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
+    # - job_name: Build Flet for macOS
+    #   job_group: build_flet
+    #   job_depends_on: build_flet_package
+    #   APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
 
-    - job_name: Build Fletd
-      job_group: build_flet
-      job_depends_on: build_flet_package
-      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+    # - job_name: Build Flet for Linux
+    #   job_group: build_flet
+    #   job_depends_on: build_flet_package
+    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004
 
-    - job_name: Test Python 3.7
-      job_group: python_tests
-      job_depends_on: build_flet
-      python_stack: python 3.7
-      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+    # - job_name: Build Flet for Linux ARM64
+    #   job_group: build_flet
+    #   job_depends_on: build_flet_package
+    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004-arm
+    #   python_stack: ""
 
-    - job_name: Test Python 3.8
-      job_group: python_tests
-      job_depends_on: build_flet
-      python_stack: python 3.8
-      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+    # - job_name: Build Flet for iOS
+    #   job_group: build_flet
+    #   job_depends_on: build_flet_package
+    #   APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
 
-    - job_name: Test Python 3.9
-      job_group: python_tests
-      job_depends_on: build_flet
-      python_stack: python 3.9
-      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+    # - job_name: Build Fletd
+    #   job_group: build_flet
+    #   job_depends_on: build_flet_package
+    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
 
-    - job_name: Test Python 3.10
-      job_group: python_tests
-      job_depends_on: build_flet
-      python_stack: python 3.10
-      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+    # - job_name: Test Python 3.7
+    #   job_group: python_tests
+    #   job_depends_on: build_flet
+    #   python_stack: python 3.7
+    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
 
-    - job_name: Build Python wheels
-      job_group: python_build
-      job_depends_on: python_tests
-      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
-      TWINE_USERNAME: __token__
-      TWINE_NON_INTERACTIVE: true
-      pypi_key:
-        secure: 174ncAbF5IjSIkmioPt62jeSnzmTlRNchUkE4QdjDWH8xK1olYtySXLJpo2q95HcP7lWJky1hv4APESiRRHnBWoY0XRFafzM/mbCDMzG1tZXiXZmpP1qzHAtRP2QSCIg18xh1TMktraUdTi7sbJnjjRhqzgbW1k0kLBxKw79MPFBhYQ/TiGcmaYWZbWVZNY3HCUCb6Dt7bG1OE2Ul9rD1gvs55xwO9Oq9FOVA1VnMYw=
-      test_pypi_key:
-        secure: cMCzqE9PcLcAiQ7POU0eVmLsXpy/n3WA9USIQNDKKbvUeajtURVITKpQ4MmwUXZAGv8giPPDUppiIf22AwIfx3O43tBVCp/HjvKNCbgY8sTaQBx60mLRbVBfD1F/+VfeuSTm57qtuSxUkZWF1JlWp8UQqIwCMHHDd0/wqDfmPNKj6U617Lp3vIfhsfgaDofspCKSGfG8+Z+6gcpmI+mA1wFHQB+l/BAbsGbgih8HiH6EzcuyIphxQKEA6r2XDPWE
+    # - job_name: Test Python 3.8
+    #   job_group: python_tests
+    #   job_depends_on: build_flet
+    #   python_stack: python 3.8
+    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+
+    # - job_name: Test Python 3.9
+    #   job_group: python_tests
+    #   job_depends_on: build_flet
+    #   python_stack: python 3.9
+    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+
+    # - job_name: Test Python 3.10
+    #   job_group: python_tests
+    #   job_depends_on: build_flet
+    #   python_stack: python 3.10
+    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+
+    # - job_name: Build Python wheels
+    #   job_group: python_build
+    #   job_depends_on: python_tests
+    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
+    #   TWINE_USERNAME: __token__
+    #   TWINE_NON_INTERACTIVE: true
+    #   pypi_key:
+    #     secure: 174ncAbF5IjSIkmioPt62jeSnzmTlRNchUkE4QdjDWH8xK1olYtySXLJpo2q95HcP7lWJky1hv4APESiRRHnBWoY0XRFafzM/mbCDMzG1tZXiXZmpP1qzHAtRP2QSCIg18xh1TMktraUdTi7sbJnjjRhqzgbW1k0kLBxKw79MPFBhYQ/TiGcmaYWZbWVZNY3HCUCb6Dt7bG1OE2Ul9rD1gvs55xwO9Oq9FOVA1VnMYw=
+    #   test_pypi_key:
+    #     secure: cMCzqE9PcLcAiQ7POU0eVmLsXpy/n3WA9USIQNDKKbvUeajtURVITKpQ4MmwUXZAGv8giPPDUppiIf22AwIfx3O43tBVCp/HjvKNCbgY8sTaQBx60mLRbVBfD1F/+VfeuSTm57qtuSxUkZWF1JlWp8UQqIwCMHHDd0/wqDfmPNKj6U617Lp3vIfhsfgaDofspCKSGfG8+Z+6gcpmI+mA1wFHQB+l/BAbsGbgih8HiH6EzcuyIphxQKEA6r2XDPWE
 
 matrix:
   fast_finish: true
@@ -282,6 +288,49 @@ for:
       artifact: flet_linux_arm64
       on:
         APPVEYOR_REPO_TAG: true
+
+  # ======================================
+  #      Build Flet Studio for iOS
+  # ======================================
+
+  - matrix:
+      only:
+        - job_name: Build Flet Studio for iOS
+
+    install:
+      - export LANG=en_US.UTF-8
+      - curl $FLUTTER_MACOS_URL -o "$HOME/flutter_macos_stable.zip"
+      - unzip -qq "$HOME/flutter_macos_stable.zip" -d $HOME
+      - export PATH="$PATH:$HOME/flutter/bin"
+      - flutter channel stable
+      - flutter upgrade
+      - flutter doctor
+
+    build_script:
+      - cd studio/client/ios
+      - ruby --version
+      - bundle install
+      - sh: |
+          export FLET_PACKAGE_VERSION="${APPVEYOR_BUILD_VERSION}"
+          if [[ ! -z "$APPVEYOR_PULL_REQUEST_NUMBER" ]]; then
+            bundle exec fastlane build_flutter      
+          elif [[ "$APPVEYOR_REPO_TAG" == "true" ]]; then
+            if [[ "$APPVEYOR_REPO_TAG_NAME" =~ ([0-9\.]+) ]]; then
+                export FLET_PACKAGE_VERSION="${BASH_REMATCH[1]}"
+                echo "FLET_PACKAGE_VERSION: ${FLET_PACKAGE_VERSION}"
+                export ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD=true
+                bundle exec fastlane upload_appstore
+            else
+                echo "Cannot extract version information from a tag."
+                exit 1
+            fi
+          else
+            bundle exec fastlane build_ipa
+          fi
+
+    artifacts:
+      - path: client/build/flet-studio.ipa
+        name: flet_studio_ios
 
   # ======================================
   #      Build Flet View for iOS
